services:
  - type: web
    name: 3d-model-platform-api
    runtime: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://lakshaychetal482:xrcVoybM2f2ETMhr@clusterrk.de7xair.mongodb.net/3d-model-platform?retryWrites=true&w=majority&appName=Clusterrk
      - key: UPLOAD_DIR
        value: /opt/render/project/src/backend/uploads
      - key: FRONTEND_URL
        value: https://frontend-eu4sd69xi-lakshay-chetals-projects.vercel.app 